### ISSUE TITLE
Error when using QUnit noGlobals option

### ISSUE THREAD

**Issue by ArchCodeMonkey** [sbrandwoo/grunt-qunit-junit#20]
Since updating I've been getting the error:

>Fatal error: Unable to write "test\reports\javascript\TEST-utilities.html?noglobals=.xml" file (Error code: ENOENT).

![error](https://cloud.githubusercontent.com/assets/11328425/7214021/7c7c8852-e5d8-11e4-813a-db0c8e887ef5.png)

If I remove the noGlobals option from the qunit task then the report file is written successfully.

![noglobals](https://cloud.githubusercontent.com/assets/11328425/7214058/f16c1a04-e5da-11e4-8df2-06ab057bcaf2.png)

I believe it is failing because the default for `option.fileNamer` uses the regex `/\.html$/` and this does not account for the query string after the file name. I was able to use the fileNamer option to remove the extra text and successfully write the report file.

```javascript
fileNamer: function (sTestPath)
{
   var sFileName = sTestPath.substring(sTestPath.lastIndexOf('/') + 1);
   var nEndIndex = sFileName.indexOf('.html');
   return (nEndIndex === -1) ? sFileName : sFileName.substring(0, nEndIndex);;
},
```

![filenamer](https://cloud.githubusercontent.com/assets/11328425/7214059/fae7e4a0-e5da-11e4-96be-e95a5ca2045e.png)

**Comment by jonnyreeves** [comment]
Thanks for the detailed bug report @ArchCodeMonkey.

Your suggestion of modifying the default `fileNamer` function to chomp everything after the query sounds sensible and should be fairly trivial to address over the weekend.
